module.exports = {
	'Emp'          : 'Employment: Counts',
	'EmpEnd'       : 'Employment end-of-quarter: Counts',
	'EmpS'         : 'Employment stable jobs: Counts',
	'EmpTotal'     : 'Employment reference quarter: Counts',
	'EmpSpv'       : 'Employment stable jobs - previous quarter: Counts',
	'HirA'         : 'Hires All: Counts',
	'HirN'         : 'Hires New: Counts',
	'HirR'         : 'Hires Recalls: Counts',
	'Sep'          : 'Separations: Counts',
	'HirAEnd'      : 'End-of-quarter hires',
	'SepBeg'       : 'Beginning-of-quarter separations',
	'HirAEndRepl'  : 'Replacement hires',
	'HirAEndR'     : 'End-of-quarter hiring rate',
	'SepBegR'      : 'Beginning-of-quarter separation rate',
	'HirAEndReplR' : 'Replacement hiring rate',
	'HirAS'        : 'Hires All stable jobs: Counts',
	'HirNS'        : 'Hires New stable jobs: Counts',
	'SepS'         : 'Separations stable jobs: Counts',
	'SepSnx'       : 'Separations stable jobs - next quarter: Counts',
	'TurnOvrS'     : 'Turnover stable jobs: Ratio',
	'FrmJbGn'      : 'Firm Job Gains: Counts',
	'FrmJbLs'      : 'Firm Job Loss: Counts',
	'FrmJbC'       : 'Firm jobs change: Net Change',
	'FrmJbGnS'     : 'Firm Gain stable jobs: Counts',
	'FrmJbLsS'     : 'Firm Loss stable jobs: Counts',
	'FrmJbCS'      : 'Firm stable jobs change: Net Change',
	'EarnS'        : 'Employees stable jobs: Average monthly earnings',
	'EarnBeg'      : 'Employees beginning-of-quarter : Average monthly earnings',
	'EarnHirAS'    : 'Hires All stable jobs: Average monthly earnings',
	'EarnHirNS'    : 'Hires New stable jobs: Average monthly earnings',
	'EarnSepS'     : 'Separations stable jobs: Average monthly earnings',
	'Payroll'      : 'Total quarterly payroll: Sum',
}
