module.exports = {
	'sEmp'          :  'Status: Employment: Counts',
	'sEmpEnd'       :  'Status: Employment end-of-quarter: Counts',
	'sEmpS'         :  'Status: Employment stable jobs: Counts',
	'sEmpTotal'     :  'Status: Employment reference quarter: Counts',
	'sEmpSpv'       :  'Status: Employment stable jobs - previous quarter: Counts',
	'sHirA'         :  'Status: Hires All: Counts',
	'sHirN'         :  'Status: Hires New: Counts',
	'sHirR'         :  'Status: Hires Recalls: Counts',
	'sSep'          :  'Status: Separations: Counts',
	'sHirAEnd'      :  'Status: End-of-quarter hires',
	'sSepBeg'       :  'Status: Beginning-of-quarter separations',
	'sHirAEndRepl'  :  'Status: Replacement hires',
	'sHirAEndR'     :  'Status: End-of-quarter hiring rate',
	'sSepBegR'      :  'Status: Beginning-of-quarter separation rate',
	'sHirAEndReplR' :  'Status: Replacement hiring rate',
	'sHirAS'        :  'Status: Hires All stable jobs: Counts',
	'sHirNS'        :  'Status: Hires New stable jobs: Counts',
	'sSepS'         :  'Status: Separations stable jobs: Counts',
	'sSepSnx'       :  'Status: Separations stable jobs - next quarter: Counts',
	'sTurnOvrS'     :  'Status: Turnover stable jobs: Ratio',
	'sFrmJbGn'      :  'Status: Firm Job Gains: Counts',
	'sFrmJbLs'      :  'Status: Firm Job Loss: Counts',
	'sFrmJbC'       :  'Status: Firm jobs change: Net Change',
	'sFrmJbGnS'     :  'Status: Firm Gain stable jobs: Counts',
	'sFrmJbLsS'     :  'Status: Firm Loss stable jobs: Counts',
	'sFrmJbCS'      :  'Status: Firm stable jobs change: Net Change',
	'sEarnS'        :  'Status: Employees stable jobs: Average monthly earnings',
	'sEarnBeg'      :  'Status: Employees beginning-of-quarter : Average monthly earnings',
	'sEarnHirAS'    :  'Status: Hires All stable jobs: Average monthly earnings',
	'sEarnHirNS'    :  'Status: Hires New stable jobs: Average monthly earnings',
	'sEarnSepS'     :  'Status: Separations stable jobs: Average monthly earnings',
	'sPayroll'      :  'Status: Total quarterly payroll: Sum',
}
