version: '2'
services:
    postgres:
      image: postgres:9.5
      ports:
          - "5433:5432"
      volumes:
        - ./pg_data:/data
        - ../data/bin/:/init_scripts
      env_file: "../config/postgres_db.env"
