node:
  image: avail/qwi-api-server
  ports:
      - "10101:10101"
  links:
    - postgres
  env_file: 
      - "../config/node_server.env"
      - "../config/postgres_db.env"
    
postgres:
  image: postgres:9.5
  volumes:
    - ./pg_data:/data
  env_file: "../config/postgres_db.env"
